before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm'
      - goos: windows
        goarch: 'arm64'

    binary: '{{ .ProjectName }}'

    flags:
      - -trimpath
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'
    hooks:
      post: 'upx --lzma {{ .Path }}'

archives:
  - format: binary
    replacements:
      darwin: macOS

checksum:
  algorithm: sha256
